FROM node:lts-alpine

COPY ./telegram_app ./app

WORKDIR /app

RUN cd /app && \
 npm install && \
 npm install -g vite

COPY ./scripts/entrypoint.sh /entrypoint.sh
RUN chmod +x /entrypoint.sh

CMD ["/entrypoint.sh"]
