FROM debian:buster-slim


RUN apt-get update && apt-get install -y \
    curl \
    build-essential \
    gcc \
    netcat \
    libssl-dev \
    pkg-config \
    ca-certificates \
    && apt-get clean

# install rust
RUN curl https://sh.rustup.rs -sSf | sh -s -- -y

COPY scripts /scripts
RUN chmod +x /scripts/telegram_bot

# Add Rust and Cargo to the PATH
ENV PATH="/root/.cargo/bin:/scripts:${PATH}"

WORKDIR /app
COPY telegram_bot .

RUN cargo build --release

CMD ["telegram_bot"]