#!/bin/bash
echo "🟡 starting NGROK"
ngrok http --url=woodcock-engaging-usually.ngrok-free.app nginx:80 &
sleep 5

public_url=$(curl -s http://localhost:4040/api/tunnels | jq -r '.tunnels[0].public_url')
echo "✅ Telegram APP URL: $public_url"
echo "✅ API URL: $public_url/api"


wait %1